Index Management

In [3]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

In [4]:
# loading data
dataset=load_dataset('lukebarousse/data_jobs')
df=dataset['train'].to_pandas()

'[Errno 11001] getaddrinfo failed' thrown while requesting HEAD https://huggingface.co/datasets/lukebarousse/data_jobs/resolve/ed776e5a0a8c40ea9d5efbd800772ae52e140f3e/data_jobs.py
Retrying in 1s [Retry 1/5].
Using the latest cached version of the dataset since lukebarousse/data_jobs couldn't be found on the Hugging Face Hub
Found the latest cached dataset configuration 'default' at C:\Users\Dell\.cache\huggingface\datasets\lukebarousse___data_jobs\default\0.0.0\ed776e5a0a8c40ea9d5efbd800772ae52e140f3e (last modified on Mon Jul 20 08:28:07 2026).

In [5]:
df['job_posted_date']=pd.to_datetime(df['job_posted_date'])

In [6]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
204513,Senior Data Scientist,"Senior Data Scientist - San Bruno, CA","San Bruno, CA",via SimplyHired,Full-time,False,"California, United States",2023-02-04 22:03:00,False,True,United States,NaN,NaN,NaN,Walmart,"['sql', 'r', 'python', 'scala', 'scikit-learn'...","{'analyst_tools': ['excel'], 'libraries': ['sc..."
1953,Data Analyst,2023 Experiential Internship – Supply Chain Da...,"Austin, TX",via SpotApp Jobs,Internship,False,"Texas, United States",2023-02-19 13:01:21,False,False,United States,NaN,NaN,NaN,WayUp,NaN,NaN
418364,Data Analyst,Data Analyst,"Puteaux, France",via Welcome To The Jungle,Internship,False,France,2023-11-02 16:25:17,False,False,France,NaN,NaN,NaN,Societe Generale,"['sql', 'power bi']","{'analyst_tools': ['power bi'], 'programming':..."
349595,Data Analyst,WorkatHome Data Analyst,Argentina,via JobLeads,Full-time,False,Argentina,2023-04-16 23:32:39,True,False,Argentina,NaN,NaN,NaN,WayUp,['excel'],{'analyst_tools': ['excel']}
472589,Business Analyst,Commercial Analyst Intern,Anywhere,via LinkedIn,Internship,True,Poland,2023-01-23 14:17:00,False,False,Poland,NaN,NaN,NaN,O-I,"['excel', 'word', 'powerpoint', 'sharepoint', ...","{'analyst_tools': ['excel', 'word', 'powerpoin..."
232533,Senior Data Engineer,Senior Big Data Engineer AVP,"Brentwood, UK",via KSNT Jobs,Full-time,False,United Kingdom,2023-06-12 07:33:34,False,False,United Kingdom,NaN,NaN,NaN,McGregor Boyall,"['java', 'c', 'c++', 'lua', 'python', 'scala',...","{'libraries': ['spark'], 'other': ['git'], 'pr..."
521099,Data Analyst,Analytics Solutions Associate - Chief Data Office,"Jersey City, NJ",via LinkedIn,Full-time,False,"New York, United States",2023-07-01 11:00:11,False,True,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,"['sql', 'powerpoint', 'excel', 'alteryx', 'tab...","{'analyst_tools': ['powerpoint', 'excel', 'alt..."
754756,Data Scientist,Process Analyst (1 Yr Contract),"Kingston, Jamaica",via Caribbean Jobs,Contractor,False,Jamaica,2023-11-23 20:43:14,False,False,Jamaica,NaN,NaN,NaN,Caribbean HR Solutions,['visio'],{'analyst_tools': ['visio']}
96081,Data Analyst,Business Data Analyst,"Mountain View, CA",via LinkedIn,Contractor,False,"California, United States",2023-01-13 00:01:08,True,False,United States,NaN,NaN,NaN,"Pyramid Consulting, Inc","['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
169767,Data Scientist,Torino- Data Scientist,"Turin, Metropolitan City of Turin, Italy",via Lavoro Trabajo.org,Full-time,False,Italy,2023-04-03 15:30:20,False,False,Italy,NaN,NaN,NaN,ISCS SRL,"['python', 'gdpr', 'power bi']","{'analyst_tools': ['power bi'], 'libraries': [..."

In [8]:
df.index

RangeIndex(start=0, stop=785741, step=1)

In [7]:
df.index.name # is a variable

In [9]:
df.index.name='job_index'

In [10]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [11]:
df.index.dtype

dtype('int64')

# Three methods to cover

1. df.reset_index()
2. df.set_index()
3. df.sort_index()

In [12]:
df_usa = df.loc[df['job_country'] == 'United States'].copy()

In [14]:
df_usa

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_index,,,,,,,,,,,,,,,,,
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [16]:
df_usa = df_usa.reset_index()
df_usa

,index,job_index,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,0,0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,1,3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
2,2,5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,NaN,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
3,3,6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,NaN,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
4,4,9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,NaN,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
206287,206287,785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,NaN,NaN,NaN,JPMorgan Chase & Co.,NaN,NaN
206288,206288,785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,NaN,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
206289,206289,785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
206290,206290,785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,NaN,NaN,NaN,Axelon Services Corporation,NaN,NaN
206291,206291,785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,NaN,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

set_index()

In [17]:
df_usa = df_usa.set_index('job_index')

In [19]:
df_usa

# sort_index()

In [28]:
df_usa = df.loc[df['job_country'] == 'United States'].copy()
median_pivot = df_usa.pivot_table(
    values='salary_year_avg',
    index='job_title_short',
    aggfunc=['median', 'max','min']
)
median_pivot
median_pivot

                                   median             max             min
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Business Analyst                  90000.0        387460.0         35000.0
Cloud Engineer                   116100.0        221844.0         42000.0
Data Analyst                      90000.0        375000.0         25000.0
Data Engineer                    125000.0        525000.0         23496.0
Data Scientist                   130000.0        960000.0         30000.0
Machine Learning Engineer        150000.0        315000.0         44408.5
Senior Data Analyst              110000.0        425000.0         35360.0
Senior Data Engineer             150000.0        375000.0         45000.0
Senior Data Scientist            155000.0        475000.0         55000.0
Software Engineer                130000.0        375000.0         48982.0

In [29]:
median_pivot = median_pivot.sort_values(by=('median', 'salary_year_avg'), ascending=False)
median_pivot

                                   median             max             min
                          salary_year_avg salary_year_avg salary_year_avg
job_title_short
Senior Data Scientist            155000.0        475000.0         55000.0
Machine Learning Engineer        150000.0        315000.0         44408.5
Senior Data Engineer             150000.0        375000.0         45000.0
Data Scientist                   130000.0        960000.0         30000.0
Software Engineer                130000.0        375000.0         48982.0
Data Engineer                    125000.0        525000.0         23496.0
Cloud Engineer                   116100.0        221844.0         42000.0
Senior Data Analyst              110000.0        425000.0         35360.0
Business Analyst                  90000.0        387460.0         35000.0
Data Analyst                      90000.0        375000.0         25000.0

In [31]:
median_pivot.sort_index(by='job_title_short',ascending=False)

TypeError: DataFrame.sort_index() got an unexpected keyword argument 'by'